###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID cic-dsd)
#  Generated on:      Wed May 30 09:48:27 2018
#  Design:            CHIP
#  Command:           saveIoFile -byOrder -temp CHIP.save.io
###############################################################

(globals
    version = 3
    io_order = default
)
(iopad
    (top
	(inst  name="ipad_X2"	place_status=placed )
	(inst  name="ipad_X1"	place_status=placed )
	(inst  name="ipad_X0"	place_status=placed )
	(inst  name="ipad_HALT"	place_status=placed )
	(inst  name="ipad_RESET_"	place_status=placed )
	(inst  name="pad_CoreVDD1"	cell="PADVDD" place_status=placed )
	(inst  name="pad_IOVSS8"	cell="PADIOVSS" place_status=placed )
	(inst  name="ipad_CLK"	place_status=placed )
	(inst  name="pad_IOVDD7"	cell="PADIOVDD" place_status=placed )
	(inst  name="pad_CoreVSS1"	cell="PADVSS" place_status=placed )
	(inst  name="ipad_DoDCT"	place_status=placed )
	(inst  name="ipad_Mode"	place_status=placed )
	(inst  name="pad_POC"	cell="PADIOVDDPOC" place_status=placed )
    )
    (left
	(inst  name="pad_IOVDD1"	cell="PADIOVDD" place_status=placed )
	(inst  name="ipad_X11"	place_status=placed )
	(inst  name="pad_IOVSS1"	cell="PADIOVSS" place_status=placed )
	(inst  name="ipad_X10"	place_status=placed )
	(inst  name="ipad_X9"	place_status=placed )
	(inst  name="pad_CoreVDD2"	cell="PADVDD" place_status=placed )
	(inst  name="ipad_X8"	place_status=placed )
	(inst  name="pad_CoreVSS2"	cell="PADVSS" place_status=placed )
	(inst  name="ipad_X7"	place_status=placed )
	(inst  name="ipad_X6"	place_status=placed )
	(inst  name="ipad_X5"	place_status=placed )
	(inst  name="ipad_X4"	place_status=placed )
	(inst  name="ipad_X3"	place_status=placed )
    )
    (bottom
	(inst  name="opad_Z0"	place_status=placed )
	(inst  name="pad_IOVSS2"	cell="PADIOVSS" place_status=placed )
	(inst  name="opad_Z1"	place_status=placed )
	(inst  name="pad_IOVDD2"	cell="PADIOVDD" place_status=placed )
	(inst  name="opad_Z2"	place_status=placed )
	(inst  name="pad_IOVSS3"	cell="PADIOVSS" place_status=placed )
	(inst  name="opad_Z3"	place_status=placed )
	(inst  name="pad_CoreVSS3"	cell="PADVSS" place_status=placed )
	(inst  name="opad_Z4"	place_status=placed )
	(inst  name="pad_CoreVDD3"	cell="PADVDD" place_status=placed )
	(inst  name="opad_Z5"	place_status=placed )
	(inst  name="pad_IOVDD3"	cell="PADIOVDD" place_status=placed )
	(inst  name="opad_Z6"	place_status=placed )
    )
    (right
	(inst  name="pad_IOVSS4"	cell="PADIOVSS" place_status=placed )
	(inst  name="opad_Z7"	place_status=placed )
	(inst  name="pad_IOVDD4"	cell="PADIOVDD" place_status=placed )
	(inst  name="opad_Z8"	place_status=placed )
	(inst  name="pad_IOVSS5"	cell="PADIOVSS" place_status=placed )
	(inst  name="opad_Z9"	place_status=placed )
	(inst  name="pad_IOVDD5"	cell="PADIOVDD" place_status=placed )
	(inst  name="opad_Z10"	place_status=placed )
	(inst  name="pad_IOVSS6"	cell="PADIOVSS" place_status=placed )
	(inst  name="opad_Z11"	place_status=placed )
	(inst  name="pad_IOVDD6"	cell="PADIOVDD" place_status=placed )
	(inst  name="ipad_SCAN_EN"	place_status=placed )
	(inst  name="ipad_TEST_MODE"	place_status=placed )
    )
    (topright
	(inst  name="CORNER0"	cell="PADCORNER" place_status=placed )
    )
    (topleft
	(inst  name="CORNER1"	cell="PADCORNER" place_status=placed )
    )
    (bottomright
	(inst  name="CORNER2"	cell="PADCORNER" place_status=placed )
    )
    (bottomleft
	(inst  name="CORNER3"	cell="PADCORNER" place_status=placed )
    )
)
