###############################################################
#  Generated by:      Cadence Innovus 19.12-s087_1
#  OS:                Linux x86_64(Host ID cic-dsd)
#  Generated on:      Wed Jun  3 16:30:49 2020
#  Design:            CHIP
#  Command:           saveFPlan fp1.fp
###############################################################

Version: 8

Head Box: 0.0000 0.0000 779.3800 779.3800
IO Box: 199.5000 199.5000 579.8800 579.8800
Core Box: 249.6600 249.6200 529.7200 529.6200
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: FreePDK45_38x28_10R_NP_162NW_34O 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: CORE_ROW_0 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 528.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_1 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 526.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_2 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 525.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_3 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 524.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_4 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 522.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_5 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 521.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_6 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 519.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_7 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 518.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_8 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 517.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_9 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 515.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_10 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 514.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_11 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 512.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_12 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 511.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_13 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 510.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_14 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 508.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_15 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 507.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_16 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 505.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_17 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 504.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_18 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 503.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_19 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 501.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_20 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 500.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_21 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 498.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_22 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 497.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_23 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 496.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_24 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 494.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_25 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 493.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_26 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 491.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_27 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 490.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_28 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 489.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_29 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 487.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_30 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 486.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_31 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 484.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_32 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 483.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_33 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 482.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_34 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 480.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_35 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 479.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_36 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 477.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_37 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 476.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_38 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 475.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_39 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 473.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_40 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 472.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_41 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 470.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_42 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 469.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_43 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 468.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_44 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 466.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_45 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 465.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_46 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 463.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_47 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 462.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_48 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 461.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_49 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 459.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_50 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 458.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_51 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 456.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_52 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 455.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_53 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 454.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_54 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 452.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_55 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 451.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_56 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 449.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_57 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 448.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_58 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 447.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_59 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 445.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_60 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 444.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_61 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 442.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_62 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 441.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_63 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 440.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_64 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 438.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_65 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 437.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_66 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 435.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_67 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 434.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_68 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 433.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_69 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 431.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_70 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 430.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_71 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 428.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_72 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 427.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_73 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 426.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_74 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 424.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_75 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 423.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_76 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 421.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_77 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 420.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_78 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 419.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_79 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 417.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_80 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 416.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_81 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 414.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_82 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 413.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_83 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 412.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_84 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 410.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_85 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 409.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_86 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 407.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_87 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 406.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_88 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 405.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_89 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 403.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_90 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 402.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_91 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 400.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_92 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 399.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_93 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 398.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_94 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 396.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_95 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 395.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_96 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 393.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_97 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 392.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_98 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 391.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_99 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 389.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_100 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 388.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_101 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 386.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_102 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 385.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_103 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 384.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_104 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 382.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_105 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 381.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_106 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 379.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_107 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 378.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_108 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 377.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_109 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 375.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_110 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 374.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_111 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 372.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_112 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 371.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_113 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 370.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_114 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 368.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_115 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 367.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_116 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 365.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_117 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 364.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_118 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 363.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_119 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 361.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_120 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 360.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_121 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 358.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_122 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 357.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_123 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 356.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_124 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 354.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_125 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 353.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_126 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 351.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_127 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 350.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_128 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 349.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_129 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 347.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_130 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 346.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_131 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 344.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_132 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 343.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_133 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 342.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_134 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 340.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_135 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 339.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_136 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 337.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_137 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 336.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_138 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 335.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_139 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 333.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_140 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 332.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_141 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 330.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_142 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 329.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_143 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 328.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_144 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 326.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_145 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 325.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_146 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 323.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_147 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 322.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_148 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 321.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_149 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 319.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_150 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 318.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_151 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 316.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_152 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 315.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_153 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 314.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_154 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 312.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_155 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 311.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_156 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 309.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_157 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 308.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_158 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 307.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_159 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 305.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_160 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 304.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_161 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 302.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_162 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 301.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_163 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 300.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_164 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 298.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_165 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 297.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_166 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 295.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_167 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 294.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_168 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 293.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_169 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 291.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_170 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 290.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_171 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 288.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_172 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 287.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_173 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 286.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_174 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 284.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_175 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 283.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_176 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 281.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_177 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 280.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_178 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 279.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_179 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 277.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_180 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 276.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_181 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 274.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_182 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 273.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_183 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 272.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_184 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 270.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_185 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 269.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_186 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 267.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_187 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 266.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_188 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 265.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_189 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 263.6200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_190 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 262.2200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_191 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 260.8200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_192 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 259.4200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_193 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 258.0200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_194 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 256.6200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_195 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 255.2200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_196 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 253.8200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_197 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 252.4200 FS 1474 1 0.1900 0.0000
DefRow: CORE_ROW_198 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 251.0200 N 1474 1 0.1900 0.0000
DefRow: CORE_ROW_199 FreePDK45_38x28_10R_NP_162NW_34O 249.6600 249.6200 FS 1474 1 0.1900 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: Y 1.6900 487 1.6000 1 10
Track: X 1.1150 464 1.6800 1 10
Track: X 1.1150 927 0.8400 1 9
Track: Y 1.6900 487 1.6000 1 9
Track: Y 1.0500 927 0.8400 1 8
Track: X 1.1150 927 0.8400 1 8
Track: X 0.2750 2783 0.2800 1 7
Track: Y 1.0500 927 0.8400 1 7
Track: Y 0.2100 2783 0.2800 1 6
Track: X 0.2750 2783 0.2800 1 6
Track: X 0.2750 2783 0.2800 1 5
Track: Y 0.2100 2783 0.2800 1 5
Track: Y 0.0700 5567 0.1400 1 4
Track: X 0.2750 2783 0.2800 1 4
Track: X 0.0950 4102 0.1900 1 3
Track: Y 0.0700 5567 0.1400 1 3
Track: Y 0.0700 5567 0.1400 1 2
Track: X 0.0950 4102 0.1900 1 2
Track: X 0.0950 4102 0.1900 1 1
Track: Y 0.0700 5567 0.1400 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: Y 0.0000 2 0.0700
GCellGrid: Y 0.0700 557 1.4000
GCellGrid: Y 778.4700 2 0.9100
GCellGrid: X 0.0000 2 0.0950
GCellGrid: X 0.0950 411 1.9000
GCellGrid: X 779.0950 2 0.2850

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################
ScanGroup: scan1_seg1_CLK_rising ipad_X0/C u_IDCT/DRU/LIFO_reg[0][10]/SI
ScanGroup: scan2_seg1_CLK_falling ipad_X1/C u_IDCT/tposemem_Bisted_RF_2P_ADV64x16_BistCtrl_i0_ST_MAL_i0_S17_reg/SI
ScanGroup: scan3_seg1_CLK_rising ipad_X2/C d_X_reg[11]/SI

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#####################################################################################
# <PGNets>                                                                          #
#    <PGNet name="net_name">                                                        #
#       <HNet name="hnet_name">                                                     #
#          <Port hinst="hinst_name" name="port_name" direction="in|out|inout" />    #
#       </HNet>                                                                     #
#    </PGNet>                                                                       #
# </PGNets>                                                                         #
#####################################################################################

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################

###########################################################################
#  <macro_place_constraint>                                               #
#          ...                                                            #
#  </macro_place_constraint>                                              #
###########################################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################
Block: u_DCT/tposemem_Bisted_RF_2P_ADV64x16_RF_2P_ADV64x16_u0_SRAM_i0 R0 454.3800 478.4200 00
Block: u_IDCT/tposemem_Bisted_RF_2P_ADV64x16_RF_2P_ADV64x16_u0_SRAM_i0 R0 249.6600 251.5550 00

###########################################################################
#  BlockRoutingHalo: <name> <space> <bottomLayer> <topLayer> <-lithoHalo> #
###########################################################################
BlockRoutingHalo: u_DCT/tposemem_Bisted_RF_2P_ADV64x16_RF_2P_ADV64x16_u0_SRAM_i0 0.5000 M1 M10
BlockRoutingHalo: u_IDCT/tposemem_Bisted_RF_2P_ADV64x16_RF_2P_ADV64x16_u0_SRAM_i0 0.5000 M1 M10

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinSpacing layer=layerId spacing=val />                        #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d spacing=val />   #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="CHIP" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x3ff orient=R0>
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################################
#  <RouteBlockages>                                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes coreeolblkg=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                                      #
#     </Blockage>                                                                                                        #
#  </RouteBlockages>                                                                                                     #
##########################################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: fp1.fp.spr

#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: pad_CoreVDD1 PADVDD 345.8000 579.8800 N R180 - 00
IO: pad_IOVSS8 PADIOVSS 375.0600 579.8800 N R180 - 00
IO: pad_IOVDD7 PADIOVDD 433.5800 579.8800 N R180 - 00
IO: pad_CoreVSS1 PADVSS 462.8400 579.8800 N R180 - 00
IO: pad_POC PADIOVDDPOC 550.6200 579.8800 N R180 - 00
IO: CORNER0 PADCORNER 579.8800 579.8800 NE R180 - 00
IO: ipad_X2 PADIN 199.5000 579.8800 N R180 - 00
IO: ipad_X1 PADIN 228.7600 579.8800 N R180 - 00
IO: ipad_X0 PADIN 258.0200 579.8800 N R180 - 00
IO: ipad_RESET_ PADIN 316.5400 579.8800 N R180 - 00
IO: ipad_Mode PADIN 521.3600 579.8800 N R180 - 00
IO: ipad_HALT PADIN 287.2800 579.8800 N R180 - 00
IO: ipad_DoDCT PADIN 492.1000 579.8800 N R180 - 00
IO: ipad_CLK PADIN 404.3200 579.8800 N R180 - 00
IO: pad_IOVDD1 PADIOVDD 0.0000 199.5000 W R270 - 00
IO: pad_IOVSS1 PADIOVSS 0.0000 258.0200 W R270 - 00
IO: pad_CoreVDD2 PADVDD 0.0000 345.8000 W R270 - 00
IO: pad_CoreVSS2 PADVSS 0.0000 404.3200 W R270 - 00
IO: CORNER1 PADCORNER 0.0000 579.8800 NW R270 - 00
IO: ipad_X11 PADIN 0.0000 228.7600 W R270 - 00
IO: ipad_X10 PADIN 0.0000 287.2800 W R270 - 00
IO: ipad_X9 PADIN 0.0000 316.5400 W R270 - 00
IO: ipad_X8 PADIN 0.0000 375.0600 W R270 - 00
IO: ipad_X7 PADIN 0.0000 433.5800 W R270 - 00
IO: ipad_X6 PADIN 0.0000 462.8400 W R270 - 00
IO: ipad_X5 PADIN 0.0000 492.1000 W R270 - 00
IO: ipad_X4 PADIN 0.0000 521.3600 W R270 - 00
IO: ipad_X3 PADIN 0.0000 550.6200 W R270 - 00
IO: pad_IOVSS2 PADIOVSS 228.7600 0.0000 S R0 - 00
IO: pad_IOVDD2 PADIOVDD 287.2800 0.0000 S R0 - 00
IO: pad_IOVSS3 PADIOVSS 345.8000 0.0000 S R0 - 00
IO: pad_CoreVSS3 PADVSS 404.3200 0.0000 S R0 - 00
IO: pad_CoreVDD3 PADVDD 462.8400 0.0000 S R0 - 00
IO: pad_IOVDD3 PADIOVDD 521.3600 0.0000 S R0 - 00
IO: CORNER3 PADCORNER 0.0000 0.0000 SW R0 - 00
IO: opad_Z6 PADOUT 550.6200 0.0000 S R0 - 00
IO: opad_Z5 PADOUT 492.1000 0.0000 S R0 - 00
IO: opad_Z4 PADOUT 433.5800 0.0000 S R0 - 00
IO: opad_Z3 PADOUT 375.0600 0.0000 S R0 - 00
IO: opad_Z2 PADOUT 316.5400 0.0000 S R0 - 00
IO: opad_Z1 PADOUT 258.0200 0.0000 S R0 - 00
IO: opad_Z0 PADOUT 199.5000 0.0000 S R0 - 00
IO: pad_IOVSS4 PADIOVSS 579.8800 199.5000 E R90 - 00
IO: pad_IOVDD4 PADIOVDD 579.8800 258.0200 E R90 - 00
IO: pad_IOVSS5 PADIOVSS 579.8800 316.5400 E R90 - 00
IO: pad_IOVDD5 PADIOVDD 579.8800 375.0600 E R90 - 00
IO: pad_IOVSS6 PADIOVSS 579.8800 433.5800 E R90 - 00
IO: pad_IOVDD6 PADIOVDD 579.8800 492.1000 E R90 - 00
IO: CORNER2 PADCORNER 579.8800 0.0000 SE R90 - 00
IO: opad_Z11 PADOUT 579.8800 462.8400 E R90 - 00
IO: opad_Z10 PADOUT 579.8800 404.3200 E R90 - 00
IO: opad_Z9 PADOUT 579.8800 345.8000 E R90 - 00
IO: opad_Z8 PADOUT 579.8800 287.2800 E R90 - 00
IO: opad_Z7 PADOUT 579.8800 228.7600 E R90 - 00
IO: ipad_TEST_MODE PADIN 579.8800 550.6200 E R90 - 00
IO: ipad_SCAN_EN PADIN 579.8800 521.3600 E R90 - 00

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="CLK" status="fixed" >
  </Pin>
  <Pin name="HALT" status="fixed" >
  </Pin>
  <Pin name="RESET_" status="fixed" >
  </Pin>
  <Pin name="DoDCT" status="fixed" >
  </Pin>
  <Pin name="X[11]" status="fixed" >
  </Pin>
  <Pin name="X[10]" status="fixed" >
  </Pin>
  <Pin name="X[9]" status="fixed" >
  </Pin>
  <Pin name="X[8]" status="fixed" >
  </Pin>
  <Pin name="X[7]" status="fixed" >
  </Pin>
  <Pin name="X[6]" status="fixed" >
  </Pin>
  <Pin name="X[5]" status="fixed" >
  </Pin>
  <Pin name="X[4]" status="fixed" >
  </Pin>
  <Pin name="X[3]" status="fixed" >
  </Pin>
  <Pin name="X[2]" status="fixed" >
  </Pin>
  <Pin name="X[1]" status="fixed" >
  </Pin>
  <Pin name="X[0]" status="fixed" >
  </Pin>
  <Pin name="Z[11]" status="fixed" >
  </Pin>
  <Pin name="Z[10]" status="fixed" >
  </Pin>
  <Pin name="Z[9]" status="fixed" >
  </Pin>
  <Pin name="Z[8]" status="fixed" >
  </Pin>
  <Pin name="Z[7]" status="fixed" >
  </Pin>
  <Pin name="Z[6]" status="fixed" >
  </Pin>
  <Pin name="Z[5]" status="fixed" >
  </Pin>
  <Pin name="Z[4]" status="fixed" >
  </Pin>
  <Pin name="Z[3]" status="fixed" >
  </Pin>
  <Pin name="Z[2]" status="fixed" >
  </Pin>
  <Pin name="Z[1]" status="fixed" >
  </Pin>
  <Pin name="Z[0]" status="fixed" >
  </Pin>
  <Pin name="Mode" status="fixed" >
  </Pin>
  <Pin name="TEST_MODE" status="fixed" >
  </Pin>
  <Pin name="SCAN_EN" status="fixed" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <inst name="u_DCT/tposemem_Bisted_RF_2P_ADV64x16_RF_2P_ADV64x16_u0_SRAM_i0">
	<prop name="InstRoutingHaloBottomLayer" type=PTR value="metal1" />
	<prop name="InstRoutingHaloTopLayer" type=PTR value="metal10" />
	<prop name="InstRoutingHaloSideSize" type=Int value=1000 />
  </inst>
  <inst name="u_IDCT/tposemem_Bisted_RF_2P_ADV64x16_RF_2P_ADV64x16_u0_SRAM_i0">
	<prop name="InstRoutingHaloBottomLayer" type=PTR value="metal1" />
	<prop name="InstRoutingHaloTopLayer" type=PTR value="metal10" />
	<prop name="InstRoutingHaloSideSize" type=Int value=1000 />
  </inst>
  <Design name="CHIP">
	<prop name="CUT_ROWS" type=Int value=0 />
  </Design>
</Properties>

###########################################################$############################################################################################
#  GlobalNetConnection: <net_name> {-pin|-instanceBasename|-net} <base_name_pattern> -type {pgpin|net|tiehi|tielo} {-all|-module <name>|-region <box>} [-override] #
########################################################################################################################################################
GlobalNetConnection: VDD -pin VDD -instanceBasename * -type pgpin -all
GlobalNetConnection: VDD -pin VDDPE -instanceBasename * -type pgpin -all
GlobalNetConnection: VDD -pin VDDCE -instanceBasename * -type pgpin -all
GlobalNetConnection: VSS -pin VSS -instanceBasename * -type pgpin -all
GlobalNetConnection: VSS -pin VSSE -instanceBasename * -type pgpin -all

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################
NetProperties: VDD -special -def_prop wire_group_widest_ring dbl 39.001500
NetProperties: VSS -special -def_prop wire_group_widest_ring dbl 39.001500

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
