###############################################################
#  Generated by:      Cadence Innovus 21.13-s100_1
#  OS:                Linux x86_64(Host ID f453_server)
#  Generated on:      Fri May 12 11:21:45 2023
#  Design:            CHIP
#  Command:           saveIoFile -byOrder CHIP.save.io
###############################################################

(globals
    version = 3
    io_order = default
)
(iopad
    (top
	(inst  name="ipad_CLK"	place_status=placed )
	(inst  name="ipad_DoDCT"	place_status=placed )
	(inst  name="ipad_HALT"	place_status=placed )
	(inst  name="ipad_Mode"	place_status=placed )
	(inst  name="ipad_RESET_"	place_status=placed )
	(inst  name="ipad_SCAN_EN"	place_status=placed )
	(inst  name="ipad_TEST_MODE"	place_status=placed )
    )
    (left
	(inst  name="ipad_X0"	place_status=placed )
	(inst  name="ipad_X1"	place_status=placed )
	(inst  name="ipad_X2"	place_status=placed )
	(inst  name="ipad_X3"	place_status=placed )
	(inst  name="ipad_X4"	place_status=placed )
	(inst  name="ipad_X5"	place_status=placed )
	(inst  name="ipad_X6"	place_status=placed )
	(inst  name="ipad_X7"	place_status=placed )
    )
    (bottom
	(inst  name="ipad_X8"	place_status=placed )
	(inst  name="ipad_X9"	place_status=placed )
	(inst  name="ipad_X10"	place_status=placed )
	(inst  name="ipad_X11"	place_status=placed )
	(inst  name="opad_Z0"	place_status=placed )
	(inst  name="opad_Z1"	place_status=placed )
	(inst  name="opad_Z2"	place_status=placed )
    )
    (right
	(inst  name="opad_Z3"	place_status=placed )
	(inst  name="opad_Z4"	place_status=placed )
	(inst  name="opad_Z5"	place_status=placed )
	(inst  name="opad_Z6"	place_status=placed )
	(inst  name="opad_Z7"	place_status=placed )
	(inst  name="opad_Z8"	place_status=placed )
	(inst  name="opad_Z9"	place_status=placed )
	(inst  name="opad_Z10"	place_status=placed )
	(inst  name="opad_Z11"	place_status=placed )
    )
)
