vpx set dofile abort exit
vpx set screen display -noprogress
tclmode

# Generated by Genus(TM) Synthesis Solution 19.10-p002_1, revision 1.334b
# Generated on: Wed Jun 03 11:47:43 CST 2020 (Wed Jun 03 03:47:43 GMT 2020)

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

tcl_set_command_name_echo on

set_log_file logs_Jun03-11:41:24/intermediate2final.lec.log -replace

usage -auto -elapse

set_verification_information fv_map_CHIP_mv_db

read_implementation_information fv/CHIP -golden fv_map -revised CHIP_mv

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 4 -norelease_license
set_compare_options -threads 4

set env(RC_VERSION)     "19.10-p002_1"
set env(CDN_SYNTH_ROOT) "/cad/cadence/GENUS/GENUS_19.10.000/tools"
set CDN_SYNTH_ROOT      "/cad/cadence/GENUS/GENUS_19.10.000/tools"
set env(CW_DIR) "/cad/cadence/GENUS/GENUS_19.10.000/tools/lib/chipware"
set CW_DIR      "/cad/cadence/GENUS/GENUS_19.10.000/tools/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_notranslate_modules -library -both rf_2p_hse

add_search_path . ../library/lib ../library/lef ../library/fireice ../library/memory -library -both
read_library -liberty -both /user/DSD/nschang/work/class/innovus/Lab_nangate/genus/../library/lib/NangateOpenCellLibrary_slow.lib /user/DSD/nschang/work/class/innovus/Lab_nangate/genus/../library/lib/tpz_slow.lib /user/DSD/nschang/work/class/innovus/Lab_nangate/genus/../library/memory/rf_2p_hse_nldm_ss_0p81v_0p81v_125c_syn.lib

read_design -verilog95   -golden -lastmod -noelab fv/CHIP/fv_map.v.gz
elaborate_design -golden -root {CHIP}

read_design -verilog95   -revised -lastmod -noelab outputs_Jun03-11:41:24/CHIP_m.v
elaborate_design -revised -root {CHIP}

#add_name_alias fv/CHIP/fv_map.singlebit.original_name.alias.json.gz -golden
#set_mapping_method -alias -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge
set_flatten_model -gated_clock

#add_name_alias fv/CHIP/CHIP_mv.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff dlat -both

# Table of test_signals and related attribues
#
# Index  Pin                            Type             Dedicated  Has_fanout  Port/Pin    special test function      Dft_auto_created      User_defined  LEC_value                      
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
#  1      SCAN_EN                        shift_enable     true       false       port        none                       false                 true          auto       
#  2      TEST_MODE                      test_mode        true       false       port        none                       false                 true          auto       
#  3      RESET_                         test_mode        true       true        port        none                       false                 true          auto       
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
# Warning : Multiple pin constraints are added to the golden design.
#          The constraints needed to disable test mode are not trivial.
#          It is possible that some valid functional modes will be excluded
#          from the formal verification process.
#          Please review the constraints to ensure they are all expected
#          and appropriate.
# Warning : Multiple pin constraints are added to the revised design.
#          The constraints needed to disable test mode are not trivial.
#          It is possible that some valid functional modes will be excluded
#          from the formal verification process.
#          Please review the constraints to ensure they are all expected
#          and appropriate.
add_pin_constraints 0 {SCAN_EN} -golden
add_pin_constraints 0 {TEST_MODE} -golden
add_pin_constraints 0 {SCAN_EN} -revised
add_pin_constraints 0 {TEST_MODE} -revised

set_analyze_option -auto

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information

tclmode
puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}
vpxmode
exit -f
