vpx set dofile abort exit
vpx set screen display -noprogress
tclmode

# Generated by Genus(TM) Synthesis Solution 19.10-p002_1, revision 1.334b
# Generated on: Wed Jun 03 11:46:26 CST 2020 (Wed Jun 03 03:46:26 GMT 2020)

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

tcl_set_command_name_echo on

set_log_file logs_Jun03-11:41:24/rtl2intermediate.lec.log -replace

usage -auto -elapse

set_verification_information rtl_fv_map_db

read_implementation_information fv/CHIP -revised fv_map

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 4 -norelease_license
set_compare_options -threads 4

set env(RC_VERSION)     "19.10-p002_1"
set env(CDN_SYNTH_ROOT) "/cad/cadence/GENUS/GENUS_19.10.000/tools"
set CDN_SYNTH_ROOT      "/cad/cadence/GENUS/GENUS_19.10.000/tools"
set env(CW_DIR) "/cad/cadence/GENUS/GENUS_19.10.000/tools/lib/chipware"
set CW_DIR      "/cad/cadence/GENUS/GENUS_19.10.000/tools/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_notranslate_modules -library -both rf_2p_hse

add_search_path . ../library/lib ../library/lef ../library/fireice ../library/memory -library -both
read_library -liberty -both /user/DSD/nschang/work/class/innovus/Lab_nangate/genus/../library/lib/NangateOpenCellLibrary_slow.lib /user/DSD/nschang/work/class/innovus/Lab_nangate/genus/../library/lib/tpz_slow.lib /user/DSD/nschang/work/class/innovus/Lab_nangate/genus/../library/memory/rf_2p_hse_nldm_ss_0p81v_0p81v_125c_syn.lib

set_undriven_signal 0 -golden
set_naming_style rc -golden
set_naming_rule "%s\[%d\]" -instance_array -golden
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable -golden

# Align LEC's treatment of mismatched port widths with constant
# connections with Genus's. Genus message CDFG-467 and LEC message
# HRC3.6 may indicate the presence of this issue. This option is
# only available with LEC 17.20-d301 or later.
set lec_version_required "17.20301"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -const_port_extend
}
set_hdl_options -VERILOG_INCLUDE_DIR "incdir:sep:src:cwd"

delete_search_path -all -design -golden
add_search_path . ../design/RTL -design -golden
read_design   -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -verilog2k ../design/RTL/CHIP.v ../design/RTL/DCT.v ../design/RTL/DRU.v ../design/RTL/IDRU.v ../design/RTL/acc.v ../design/RTL/acf.v ../design/RTL/bdeg.v ../design/RTL/RF_2P_ADV64x16_top.v ../design/RTL/RF_2P_ADV64x16_rb.v ../design/RTL/RF_2P_ADV64x16_wrapper.v ../design/RTL/tposemem.v
add_search_path . ../design/RTL -design -golden
read_design     -merge bbox -golden -lastmod -noelab -verilog2k $CW_DIR/sim/verilog/DW02/DW02_mult_3_stage.v $CW_DIR/sim/verilog/DW03/DW03_pipe_reg.v
elaborate_design -golden -root {CHIP} -rootonly -rootonly  

read_design -verilog95   -revised -lastmod -noelab fv/CHIP/fv_map.v.gz
elaborate_design -revised -root {CHIP}

uniquify -all -nolib -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge
set_flatten_model -gated_clock

#add_name_alias fv/CHIP/fv_map.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff dlat -both

# Table of test_signals and related attribues
#
# Index  Pin                            Type             Dedicated  Has_fanout  Port/Pin    special test function      Dft_auto_created      User_defined  LEC_value                      
#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
#  1      SCAN_EN                        shift_enable     true       false       port        none                       false                 true          auto       
#  2      TEST_MODE                      test_mode        true       false       port        none                       false                 true          auto       
#  3      RESET_                         test_mode        true       true        port        none                       false                 true          auto       
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
# Warning : Multiple pin constraints are added to the golden design.
#          The constraints needed to disable test mode are not trivial.
#          It is possible that some valid functional modes will be excluded
#          from the formal verification process.
#          Please review the constraints to ensure they are all expected
#          and appropriate.
# Warning : Multiple pin constraints are added to the revised design.
#          The constraints needed to disable test mode are not trivial.
#          It is possible that some valid functional modes will be excluded
#          from the formal verification process.
#          Please review the constraints to ensure they are all expected
#          and appropriate.
add_pin_constraints 0 {SCAN_EN} -golden
add_pin_constraints 0 {TEST_MODE} -golden
add_pin_constraints 0 {SCAN_EN} -revised
add_pin_constraints 0 {TEST_MODE} -revised

add_module_attribute DW02__DW02_mult_3_stage__builtin_A_width17_B_width9 DW02__DW02_mult_3_stage__builtin_A_width17_B_width10 DW02__DW02_mult_3_stage__builtin_A_width17_B_width15 DW02__DW02_mult_3_stage__builtin_A_width17_B_width13 DW02__DW02_mult_3_stage__builtin_A_width17_B_width14 DW02__DW02_mult_3_stage__builtin_A_width17_B_width14_1 DW02__DW02_mult_3_stage__builtin_A_width17_B_width13_1 DW02__DW02_mult_3_stage__builtin_A_width17_B_width9_1 DW02__DW02_mult_3_stage__builtin_A_width17_B_width10_1 DW02__DW02_mult_3_stage__builtin_A_width17_B_width15_1 DW02__DW02_mult_3_stage__builtin_A_width17_B_width13_2 DW02__DW02_mult_3_stage__builtin_A_width17_B_width14_2 DW02__DW02_mult_3_stage__builtin_A_width17_B_width14_3 DW02__DW02_mult_3_stage__builtin_A_width17_B_width13_3 -pipeline_retime -both
add_noblack_box DW02__DW02_mult_3_stage__builtin_A_width17_B_width9 DW02__DW02_mult_3_stage__builtin_A_width17_B_width10 DW02__DW02_mult_3_stage__builtin_A_width17_B_width15 DW02__DW02_mult_3_stage__builtin_A_width17_B_width13 DW02__DW02_mult_3_stage__builtin_A_width17_B_width14 DW02__DW02_mult_3_stage__builtin_A_width17_B_width14_1 DW02__DW02_mult_3_stage__builtin_A_width17_B_width13_1 DW02__DW02_mult_3_stage__builtin_A_width17_B_width9_1 DW02__DW02_mult_3_stage__builtin_A_width17_B_width10_1 DW02__DW02_mult_3_stage__builtin_A_width17_B_width15_1 DW02__DW02_mult_3_stage__builtin_A_width17_B_width13_2 DW02__DW02_mult_3_stage__builtin_A_width17_B_width14_2 DW02__DW02_mult_3_stage__builtin_A_width17_B_width14_3 DW02__DW02_mult_3_stage__builtin_A_width17_B_width13_3 -submodules -both
set_retiming_option -auto -retimed_module

set_analyze_option -auto

write_hier_compare_dofile hier_tmp2.lec.do -noexact_pin_match -constraint -usage -replace -balanced_extraction -input_output_pin_equivalence -prepend_string " report_unmapped_points -notmapped; analyze_datapath -module -verbose ; analyze_datapath   -verbose; "
run_hier_compare hier_tmp2.lec.do -dynamic_hierarchy

report_verification -hier -verbose
set_system_mode lec
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}

write_verification_information
report_verification_information

tclmode
puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}
vpxmode
exit -f
